const pageContent = {
    ID: {
      MonthList: ["Jan","Feb","Mar","Apr",
                  "Mei","Jun","Jul","Agu",
                  "Sep", "Okt","Nov","Des"],
      loadingMessage: "Mohon Tunggu Permintaan Anda Sedang Diproses",
      add: "Tambah",
      edit: "Ubah",
      del: "Hapus",
      save: "Simpan",
      cancel: "Batal",
      print: "Cetak",
      RO:{
          taball: "SEMUA",
          tablocal: "LOKAL",
          tabelRO: {
            fieldprocod: "Produk",
            fieldname: "Nama Produk",
            fieldstock: "Stok",
            fieldtglconfirm: "Tgl Konfirmasi",
            fieldunitOR: "Satuan Pesanan",
            fieldqtyOR: "Qty Pesanan",
            fieldlimitOR: "Batas Pesanan",
            fieldsisa: "Sisa",
            fieldprice: "Harga",
            fieldpricetot: "Total Harga",
          },
          lblgtotal: "Grand Total",
          outlet: "Outlet",
          noorder: "No Pesanan",
          status: "Status Pesanan",
          tglconfirm: "Tgl Konfirmasi",
          confirm: "Dikonfirmasi",
          product: "Produk",
          qtyOR: "Qty Pesanan",
          stock: "Stok",
          unitOR: "Satuan Pesanan",
          unitSell: "Satuan Jual",
          limitOR: "Batas Pesanan",
          sisa: "Sisa",
          lclprod: "Produk Lokal",
          price: "Harga",
          pricetot: "Total Harga",
          note: "Ket. OR",
          holdOR: "Pesanan Tertahan",
          stok: "Stok",
          minOR: "Min Pesanan",
          maxOR: "Max Pesanan",
          request: "Permintaan Baru",
          konfirmasi: "Konfirmasi",
          purchnumber: "No. Pembelian",
          purchdate: "Tgl. Pembelian",
          alocnumber: "No. Alokasi",
          alocdate: "Tgl. Alokasi",
          transnumber: "No. Transfer",
          transdate: "Tgl. Transfer",
          receivenumber: "No. Penerimaan",
          receivedate: "Tgl. Penerimaan",
          cancelcode: "Kode Pembatalan",
          canceldate: "Tgl. Pembatalan",
          usrupdate: "User Ubah",
          dateupdate: "Tgl. Ubah",
      }
    },
    EN: {
      MonthList: ["Jan","Feb","Mar","Apr",
                  "May","Jun","Jul","Aug",
                  "Sep", "Oct","Nov","Dec"],
      loadingMessage: "Please Wait Your Request is Being Processed",
      add: "Add",
      edit: "Update",
      del: "Delete",
      save: "Save",
      cancel: "Cancel",
      print: "Print",
      RO:{
          taball: "ALL",
          tablocal: "LOCAL",
          tabelRO: {
            fieldprocod: "Procode",
            fieldname: "Product Name",
            fieldstock: "Stock",
            fieldtglconfirm: "Confirm Date",
            fieldunitOR: "Order Unit",
            fieldqtyOR: "Order Qty",
            fieldlimitOR: "Order Limit",
            fieldsisa: "Remain",
            fieldprice: "Net Price",
            fieldpricetot: "Net Price Total",
          },
          lblgtotal: "Grand Total",
          outlet: "Outlet",
          noorder: "Order No",
          status: "Order Status",
          tglconfirm: "Confirm Date",
          confirm: "Comfirm By",
          product: "Procode",
          qtyOR: "Order Qty",
          stock: "Stock",
          unitOR: "Order Unit",
          unitSell: "Sell Unit",
          limitOR: "Order Limit",
          sisa: "Remain",
          lclprod: "Local Product",
          price: "Net Price",
          pricetot: "Net Price Total",
          note: "Note OR",
          holdOR: "Order Hold",
          stok: "Stock",
          minOR: "Min Order",
          maxOR: "Max Order",
          request: "New Request",
          konfirmasi: "Confirm",
          purchnumber: "Purchase No.",
          purchdate: "Purchase Date",
          alocnumber: "Alokasi No.",
          alocdate: "Alokasi Date",
          transnumber: "Transfer No.",
          transdate: "Transfer Date",
          receivenumber: "Receive No.",
          receivedate: "Receive Date",
          cancelcode: "Cancel Code",
          canceldate: "Cancel Date",
          usrupdate: "User Update",
          dateupdate: "Update Date",
      },
    },
  };
  export default pageContent;
  