const pageContent = {
    ID: {
      loadingMessage: "Mohon Tunggu Permintaan Anda Sedang Diproses",
      add: "Tambah",
      edit: "Ubah",
      del: "Hapus",
      save: "Simpan",
      cancel: "Batal",
      print: "Cetak",
      RO:{
          outlet: "Toko",
          noorder: "No Pesanan",
          status: "Status Pesanan",
          tglconfirm: "Tgl Konfirmasi",
          confirm: "Dikonfirmasi",
          product: "Produk",
          qtyOR: "Qty Pesanan",
          qty: "Qty",
          unitOR: "Satuan Pesanan",
          limitOR: "Batas Pesanan",
          sisa: "Sisa",
          price: "Harga",
          note: "Ket. OR",
          holdOR: "Pesanan Tertahan",
          stok: "Stok",
          request: "Permintaan Baru",
          konfirmasi: "Konfirmasi",
      }
    },
    EN: {
      loadingMessage: "Please Wait Your Request is Being Processed",
      add: "Add",
      edit: "Update",
      del: "Delete",
      save: "Save",
      cancel: "Cancel",
      print: "Print",
      RO:{
          outlet: "Outlet",
          noorder: "Order No",
          status: "Order Status",
          tglconfirm: "Confirm Date",
          confirm: "Comfirm By",
          product: "Procode",
          qtyOR: "Order Qty",
          qty: "Quantity",
          unitOR: "Order Unit",
          limitOR: "Order Limit",
          sisa: "Remain",
          price: "Net Price",
          note: "Note OR",
          holdOR: "Order Hold",
          stok: "Stock",
          request: "New Request",
          konfirmasi: "Confirm",
      },
    },
  };
  export default pageContent;
  