const pageContent = {
    ID: {
      MonthList: ["Jan","Feb","Mar","Apr",
                  "Mei","Jun","Jul","Agu",
                  "Sep", "Okt","Nov","Des"],
      loadingMessage: "Mohon Tunggu Permintaan Anda Sedang Diproses",
      add: "Tambah",
      edit: "Ubah",
      del: "Hapus",
      save: "Simpan",
      cancel: "Batal",
      print: "Cetak",
      RO:{
          taball: "SEMUA",
          tablocal: "LOKAL",
          tabelRO: {
            fieldprocod: "Produk",
            fieldname: "Nama Produk",
            fieldqty: "Quantity",
            fieldtglconfirm: "Tgl Konfirmasi",
            fieldunitOR: "Satuan Pesanan",
            fieldqtyOR: "Qty Pesanan",
            fieldlimitOR: "Batas Pesanan",
            fieldsisa: "Sisa",
            fieldprice: "Harga",
            fieldpricetot: "Total Harga",
          },
          lblgtotal: "Grand Total",
          outlet: "Outlet",
          noorder: "No Pesanan",
          status: "Status Pesanan",
          tglconfirm: "Tgl Konfirmasi",
          confirm: "Dikonfirmasi",
          product: "Produk",
          qtyOR: "Qty Pesanan",
          qty: "Quantity",
          unitOR: "Satuan Pesanan",
          limitOR: "Batas Pesanan",
          sisa: "Sisa",
          lclprod: "Produk Lokal",
          price: "Harga",
          usrupdate: "User Ubah",
          pricetot: "Total Harga",
          note: "Ket. OR",
          holdOR: "Pesanan Tertahan",
          stok: "Stok",
          request: "Permintaan Baru",
          konfirmasi: "Konfirmasi",
      }
    },
    EN: {
      MonthList: ["Jan","Feb","Mar","Apr",
                  "May","Jun","Jul","Aug",
                  "Sep", "Oct","Nov","Dec"],
      loadingMessage: "Please Wait Your Request is Being Processed",
      add: "Add",
      edit: "Update",
      del: "Delete",
      save: "Save",
      cancel: "Cancel",
      print: "Print",
      RO:{
          taball: "ALL",
          tablocal: "LOCAL",
          tabelRO: {
            fieldprocod: "Procode",
            fieldname: "Product Name",
            fieldqty: "Quantity",
            fieldtglconfirm: "Confirm Date",
            fieldunitOR: "Order Unit",
            fieldqtyOR: "Order Qty",
            fieldlimitOR: "Order Limit",
            fieldsisa: "Remain",
            fieldprice: "Net Price",
            fieldpricetot: "Net Price Total",
          },
          lblgtotal: "Grand Total",
          outlet: "Outlet",
          noorder: "Order No",
          status: "Order Status",
          tglconfirm: "Confirm Date",
          confirm: "Comfirm By",
          product: "Procode",
          qtyOR: "Order Qty",
          qty: "Quantity",
          unitOR: "Order Unit",
          limitOR: "Order Limit",
          sisa: "Remain",
          lclprod: "Local Product",
          price: "Net Price",
          usrupdate: "User Update",
          pricetot: "Net Price Total",
          note: "Note OR",
          holdOR: "Order Hold",
          stok: "Stock",
          request: "New Request",
          konfirmasi: "Confirm",
      },
    },
  };
  export default pageContent;
  