let data = [
  {
    procode: "100001",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },
  {
    procode: "100002",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },

  {
    procode: "100003",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },
  {
    procode: "100004",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },
  {
    procode: "100005",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },

  {
    procode: "100006",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },
  {
    procode: "100007",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },

  {
    procode: "100008",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },

  {
    procode: "100009",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },
  {
    procode: "100010",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },
];

export { data };
