let data = [
  {
    procode: "100001",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },
  {
    procode: "100002",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },

  {
    procode: "100003",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },
  {
    procode: "100004",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },
  {
    procode: "100005",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },

  {
    procode: "100006",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },
  {
    procode: "100007",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },

  {
    procode: "100008",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },

  {
    procode: "100009",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },
  {
    procode: "100010",
    "Product Description": "Sample Data",
    Quantity: "Sample Data",
    "Order Unit": "Sample Data",
    "Order Qty": "Sample Data",
    "Order Limit": "Sample Data",
    Remain: "Sample Data",
    "Net Price": "Sample Data",
  },
];

const dataOrder = [
  {
    "order number": "856001488",
    "order status": "Y",
    "confirm date": "2022-04-12 15:17:19",
    "confirm by": "P201222",
    "grand total": 500000,
  },
];

const dataProduct = [
  {
    procode: 57,
    "product description": "Ergonomic Wooden Pizza",
    "product status": false,
    "product HNA": "706.00",
    id: "1",
  },
  {
    procode: 32,
    "product description": "Intelligent Concrete Hat",
    "product status": false,
    "product HNA": "64.00",
    id: "2",
  },
  {
    procode: 75,
    "product description": "Ergonomic Frozen Sausages",
    "product status": false,
    "product HNA": "86.00",
    id: "3",
  },
  {
    procode: 61,
    "product description": "Handmade Rubber Bacon",
    "product status": false,
    "product HNA": "213.00",
    id: "4",
  },
  {
    procode: 54,
    "product description": "Handmade Soft Table",
    "product status": false,
    "product HNA": "897.00",
    id: "5",
  },
  {
    procode: 12,
    "product description": "Small Fresh Bacon",
    "product status": false,
    "product HNA": "39.00",
    id: "6",
  },
  {
    procode: 22,
    "product description": "Sleek Cotton Shoes",
    "product status": false,
    "product HNA": "603.00",
    id: "7",
  },
  {
    procode: 25,
    "product description": "Refined Frozen Cheese",
    "product status": false,
    "product HNA": "625.00",
    id: "8",
  },
  {
    procode: 13,
    "product description": "Handmade Soft Soap",
    "product status": false,
    "product HNA": "446.00",
    id: "9",
  },
  {
    procode: 75,
    "product description": "Intelligent Granite Salad",
    "product status": false,
    "product HNA": "12.00",
    id: "10",
  },
  {
    procode: 38,
    "product description": "Ergonomic Frozen Keyboard",
    "product status": false,
    "product HNA": "467.00",
    id: "11",
  },
  {
    procode: 10,
    "product description": "Sleek Plastic Keyboard",
    "product status": false,
    "product HNA": "332.00",
    id: "12",
  },
  {
    procode: 34,
    "product description": "Small Soft Tuna",
    "product status": false,
    "product HNA": "501.00",
    id: "13",
  },
  {
    procode: 44,
    "product description": "Refined Cotton Bike",
    "product status": false,
    "product HNA": "350.00",
    id: "14",
  },
  {
    procode: 56,
    "product description": "Small Cotton Towels",
    "product status": false,
    "product HNA": "63.00",
    id: "15",
  },
  {
    procode: 9,
    "product description": "Unbranded Cotton Bike",
    "product status": false,
    "product HNA": "600.00",
    id: "16",
  },
  {
    procode: 93,
    "product description": "Tasty Frozen Chicken",
    "product status": false,
    "product HNA": "961.00",
    id: "17",
  },
  {
    procode: 5,
    "product description": "Sleek Granite Gloves",
    "product status": false,
    "product HNA": "95.00",
    id: "18",
  },
  {
    procode: 9,
    "product description": "Sleek Plastic Mouse",
    "product status": false,
    "product HNA": "894.00",
    id: "19",
  },
  {
    procode: 59,
    "product description": "Gorgeous Metal Computer",
    "product status": false,
    "product HNA": "385.00",
    id: "20",
  },
  {
    procode: 5,
    "product description": "Handmade Concrete Shoes",
    "product status": false,
    "product HNA": "912.00",
    id: "21",
  },
  {
    procode: 99,
    "product description": "Generic Plastic Fish",
    "product status": false,
    "product HNA": "426.00",
    id: "22",
  },
  {
    procode: 96,
    "product description": "Gorgeous Metal Chips",
    "product status": false,
    "product HNA": "452.00",
    id: "23",
  },
  {
    procode: 25,
    "product description": "Handcrafted Metal Computer",
    "product status": false,
    "product HNA": "872.00",
    id: "24",
  },
  {
    procode: 30,
    "product description": "Ergonomic Granite Tuna",
    "product status": false,
    "product HNA": "270.00",
    id: "25",
  },
  {
    procode: 19,
    "product description": "Generic Rubber Gloves",
    "product status": false,
    "product HNA": "46.00",
    id: "26",
  },
  {
    procode: 87,
    "product description": "Incredible Plastic Mouse",
    "product status": false,
    "product HNA": "607.00",
    id: "27",
  },
  {
    procode: 56,
    "product description": "Generic Concrete Bike",
    "product status": false,
    "product HNA": "405.00",
    id: "28",
  },
  {
    procode: 61,
    "product description": "Awesome Cotton Cheese",
    "product status": false,
    "product HNA": "839.00",
    id: "29",
  },
  {
    procode: 12,
    "product description": "Awesome Cotton Hat",
    "product status": false,
    "product HNA": "921.00",
    id: "30",
  },
];

export { data, dataOrder, dataProduct };
